name: hosla_app
description: "Hosla Varta - A Flutter app for Indian senior citizens"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # HTTP and API
  http: ^1.1.0
  dio: ^5.3.2

  # Local Storage and Authentication
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0

  # Media and UI
  image_picker: ^1.0.4
  video_player: ^2.8.1
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  
  # File picking 
  file_picker: ^6.1.1

  # Audio
  just_audio: ^0.9.36
  record: ^5.0.4
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5

  # Location and Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0

  # QR Code
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

  # Permissions
  permission_handler: ^11.1.0

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0

  # Internationalization
  intl: ^0.20.2

  # Utils
  timeago: ^3.6.0
  uuid: ^4.2.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.1

  # Connectivity
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  #fonts:
   # - family: Devanagari
    #  fonts:
     #   - asset: assets/fonts/NotoSansDevanagari-Regular.ttf
      #  - asset: assets/fonts/NotoSansDevanagari-Bold.ttf
       #   weight: 700
